bgaebalja/bsherpa-frontend

src/components/common/DrawerComponent.jsx
src/components/common/MainSelectComponent.jsx
src/components/common/TextFieldComponent.jsx
src/pages/MainPage.jsx

- 상단 버튼 추가
- 중학 / 시험지 보관함
- 과목

feat(main): 메인 화면 상단 버튼 추가

---

src/components/common/ModalComponent.jsx

feat(component): 공용 컴포넌트 추가

---

src/api/userApi.js
src/components/MainComponent.jsx
src/components/common/CardComponent.jsx
src/components/common/DrawerComponent.jsx
src/components/step/StepIndexComponent.jsx
src/hooks/useCustomLogin.jsx
src/pages/MainPage.jsx
src/pages/step/Step0Page.jsx
src/pages/step/Step1Page.jsx
src/pages/step/Step2Page.jsx
src/pages/step/Step3Page.jsx
src/pages/step/StepIndexPage.jsx
src/router/root.jsx
src/router/stepRouter.jsx
src/slices/loginSlice.jsx

feat(router): 라우터 및 페이지 구조 설정

---

src/components/common/CardComponent.jsx
src/components/step/Step0Component.jsx
src/hooks/useCustomMove.jsx
src/pages/step/Step0Page.jsx
src/router/stepRouter.jsx

- Step0 라우터
- 경로 이동에 bookId 추가
- Step0 컴포넌트
- step0 컴포넌츠 추가
- 이동 훅 추가
- useCustomMove

feat(step0): 라우터 및 step0 component 추가

---

src/components/MainComponent.jsx
src/components/common/MainSelectComponent.jsx
src/router/root.jsx

- Step0 버튼 클릭 ui
- 과목 선택시 해당 버튼 아웃라인 생성

feat(step0): 과목 버튼 클릭시 아웃라인 생기는 기능 추가

---

src/components/common/CardComponent.jsx

- 시험지 만들기 클릭시 경로 수정
- 과목 이름 없이 경로 생성하도록 수정

fix(step0): 경로 수정

---

vercel.json

feat(vercel): vercel.json 추가

---

package-lock.json
package.json
src/components/common/AccordionComponent.jsx
src/components/common/DrawerComponent.jsx
src/components/common/TableComponent.jsx
src/components/step/Step0Component.jsx

feat(step0): step0 page ui 추가

---

src/components/step/Step2Component.jsx
src/pages/step/Step2Page.jsx

[#16] Step2 기본 구조 생성

---

src/components/step/Step2Component.jsx

[#18] Step2 컴포넌트에 CSS 적용

---

src/components/step/Step2Component.jsx

- VITE_COMMON_LINK
- VITE_FONT_LINK
- VITE_RESET_LINK

[#20] S3 URL 환경변수화

---

package-lock.json
package.json
src/api/Step1Api.js
src/components/step/step1/Step1Component.jsx
src/index.css
src/main.jsx
src/pages/step/Step1Page.jsx
vite.config.js

feat: Step1 데이터 및 아코디언 UI완성 후 fitstCommit

feat: Step1 데이터 및 아코디언 UI완성 후 fitstCommit

---

src/components/step/step1/Step1Component.jsx

Step1 API URL FIX

---

src/components/common/TableComponent.jsx
src/components/step/Step0Component.jsx

feat(step0): 선택한 row에서 examId 추출

---

src/components/common/TableComponent.jsx
src/components/step/Step0Component.jsx
src/hooks/useCustomMove.jsx
src/store.jsx

- step0 페이지 시험지 만들기 버튼
- 버튼 클릭시 step1 이동

feat(step0): step0 페이지에서 시험지 만들기 버튼

---

src/components/step/StepIndexComponent.jsx
src/pages/step/Step2Page.jsx
src/pages/step/StepIndexPage.jsx

refactor(step0): 불필요한 문구 삭제

---

src/pages/Error404.jsx
src/router/root.jsx

feat(404): 404 error 페이지

---

src/components/step/step1/Step1Component.jsx

feat: 부모 체크 박스 선택 수정

---

src/api/userApi.js
src/components/MainComponent.jsx
src/components/common/DrawerComponent.jsx
src/components/common/TextFieldComponent.jsx
src/components/user/JoinComponent.jsx
src/layouts/BasicLayout.jsx
src/pages/MainPage.jsx
src/pages/user/JoinPage.jsx
src/router/root.jsx

feat(user): 회원 가입 및 로그인 기능 추가

---

src/components/common/DrawerComponent.jsx
src/pages/step/Step0Page.jsx

- 로그인시 로그인 창 변경
- 로그인 후 로그아웃으로 바뀌도록 추가

feat(user): 로그인시 로그인 창 변경 기능 추가

---

src/components/common/DrawerComponent.jsx
src/components/user/JoinComponent.jsx

feat(user): 회원가입 성공시 메인페이지로 보내는 기능 추가

---

src/api/config.js
src/api/mainApi.js
src/api/step0Api.js
src/components/MainComponent.jsx
src/components/common/MainSelectComponent.jsx

feat(main): 메인 페이지

---

src/components/MainComponent.jsx
src/components/common/DrawerComponent.jsx
src/hooks/useCustomMove.jsx

feat(main): 메인 페이지 과목 한 번 더 선택해도 선택 되도록 수정

---

src/api/step0Api.js
src/components/step/Step0Component.jsx

feat(step0): step0 페이지 서버에서 데이터 받아오도록 추가

---

src/components/MainComponent.jsx

- CardComponent 사이 간격 추가
- marginTop: 2
- marginBottom: 2

refactor(main): CardComponent 사이 간격 추가

---

src/components/MainComponent.jsx

- CardComponent 1 row 당 4개 나오도록 수정
- 5개에서 4개로 수정

refactor(main): CardComponent 1 row 당 4개씩 나오게 수정

---

src/components/step/Step2Component.jsx
src/components/step/Step3Component.jsx
src/components/step/step1/Step1Component.jsx
src/util/CommonResource.jsx

- CommonResource.jsx
- INPUT_CHECKBOX_IMAGE
- SELECT_ARROW_IMAGE
- Step1, Step2, Step3에 적용

[#41] 공통 리소스 경로 컴포넌트 분리, input checkbox 이미지와 select arrow 이미지 경로 환경변수 추가

---

src/util/CommonResource.jsx

[#41, #42] 누락된 환경변수 importing 추가

---

.gitignore
src/api/config.js
src/api/step2Api.js
src/components/step/Step2Component.jsx

- 교재 ID를 통해 평가 영역 목록을 가져 오는 기능
- 평가 영역 ID, 난이도 별 문제 수, 단원 코드 정보, 문제 유형을 통해 문제 이미지 목록을 가져 오는 기능
- 가져 온 문제 이미지 목록을 좌측 페이지에 표시하는 기능

[#44] Step2의 문제 이미지 목록 데이터 받아 오기, 문제 이미지 목록 표시 기능 추가

---

src/components/MainComponent.jsx
src/components/common/CardComponent.jsx
src/components/common/MainSelectComponent.jsx
src/components/step/Step0Component.jsx
src/hooks/useCustomMove.jsx
src/router/root.jsx
src/router/stepRouter.jsx
src/slices/bookIdSlice.jsx
src/store.jsx

- main
- '/:subjectName' -> '/' 로 수정
- step0
- 'exam/step0/:bookId' -> 'exam/step0' 로 수정
- bookIdSlice 추가

refactor(step0): 엔드 포인트 수정 및 bookIdSlice 추가

---

src/components/common/TableComponent.jsx

refactor(step): 문항정보표 버튼 제거

---

src/components/common/CardComponent.jsx
src/components/step/Step0Component.jsx

- step0 단원 선택 화면 정보 추가
- 교재 이름
- 교재 저자

feat(step0): step0 단원 선택 화면 정보 추가

---

src/components/common/TableComponent.jsx
src/components/step/Step0Component.jsx
src/components/step/Step2Component.jsx
src/components/step/step1/Step1Component.jsx
src/slices/examIdSlice.jsx

- step0 단원 선택 수정
- 다른 단원을 선택해도 examIdList 에 추가
- step0 에서 교재명과 저자명 표기 UI 변경

refactor(step0): step0 단원 선택

---

src/components/common/TableComponent.jsx

feat(step0): 테이블 수정 불가능하게 구현

---

src/components/step/Step2Component.jsx

[#59] Step2에서 Step1으로 되돌아가는 기능 추가

---

src/components/step/Step2Component.jsx
src/components/step/Step3Component.jsx

[#60] Step2에서 구성된 문제 데이터 목록을 Step3로 전송하는 기능 추가

---

src/components/step/Step2Component.jsx
src/components/step/Step3Component.jsx

[#64] Step2에서 Step3로 전송하는 데이터에 교재 ID 추가

---

src/util/CommonResource.jsx

[#67] CSS에 적용되는 이미지 경로를 S3 버킷 내부에서 참조하도록 변경

---

src/components/step/Step2Component.jsx

[#69] Step2의 난이도와 문제 유형이 실제 데이터를 반영하도록 변경

---

src/api/step2Api.js
src/components/step/Step2Component.jsx

[#71] Step2의 과목명과 저자명, 년도 정보가 실제 데이터를 반영하도록 변경

---

src/components/step/Step2Component.jsx

[#73] Step2의 난이도 별 문제 수와 전체 문제 수가 실제 데이터를 반영하도록 변경

---

src/components/step/Step2Component.jsx

[#75] Step2의 대중소토 단원명이 실제 데이터를 반영하도록 변경

---

src/components/step/Step2Component.jsx

[#77] Step2의 정답과 해설이 실제 데이터를 반영하도록 변경

---

.gitignore
src/assets/css/confirmationModal.css
src/components/common/ConfirmationModal.jsx
src/components/step/Step2Component.jsx

- ConfirmationModal.jsx
- confirmationModal.css

[#79] Step2 페이지에서 재검색 버튼 클릭 시 새로운 랜덤 문제들을 가져 오는 기능 추가

---

src/components/step/Step2Component.jsx

[#81] Step2의 문제만 보기, 문제+정답 보기, 문제+해설+정답 보기 기능 추가

---

src/components/step/Step2Component.jsx

[#85] Step2에 지문과 문제를 함께 표시하는 기능 추가

---

.gitignore
src/components/step/Step2Component.jsx
src/components/step/Step3Component.jsx
src/slices/examDataSlice.js
src/store.jsx

- examDataSlice.js
- store.jsx
- Step3Component.jsx

[#87] Step2에서 교재 ID와 지문, 문제 데이터를 전역으로 등록하도록 설정, Redux 적용, Step3에서 데이터 수신

---

src/components/step/Step2Component.jsx

- sortGroupedItems 변수를 트리깅하는 useEffect의 의존성 배열에서 groupedItems 변수 제거
- isSorted 상태를 사용해 최초 groupedItems업데이트 시 한 번만 단원순으로 정렬하고, 이후 groupedItems가 업데이트될 때 반복적으로 정렬하지 않도록 수정

[#93] Step2에서 초기 렌더링 시 단원순 정렬을 반복하며 끊임없이 리렌더링 되는 문제 해결

---

src/components/step/Step2Component.jsx
src/components/step/Step2RightSideComponent.jsx

[#95] Step2의 오른쪽 파트 시험지 요약 목록 기능 추가

---

src/components/step/Step2Component.jsx
src/components/step/Step2RightSideComponent.jsx

[#97] Step2의 오른쪽 파트 문제 클릭 시 왼쪽 파트의 해당 문제로 이동하는 기능 추가

---

src/components/step/Step2RightSideComponent.jsx

[#99] Step2의 오른쪽 파트의 햄버거 바 지문 합치기 기능 추가

---

src/components/step/Step2Component.jsx
src/components/step/Step2RightSideComponent.jsx

[#101] Step2의 시험지 요약 목록에서 지문 별로 인덱스가 이어지지 않는 문제와 정렬이 다르게 되는 문제 해결

---

package-lock.json
package.json
src/components/step/Step2Component.jsx
src/components/step/Step2RightSideComponent.jsx

- react-beautiful-dnd 의존성
- Drag & Drop을 통해 지문의 순서를 변경하는 기능
- Drag & Drop을 통해 지문 내 문제 순서를 변경하는 기능
- 문제를 다른 지문의 하위로 이동하려 할 시 이동되지 않도록 방지하고 모달창 알림

[#103] Step2의 시험지 요약 목록에서 햄버거 바의 드래그 앤 드랍을 통해 지문 간/문제 간 순서를 이동하는 기능 추가

---

src/components/step/Step2Component.jsx
src/components/step/Step2RightSideComponent.jsx

[#105] itemId가 undefined일 때 문제 드래그 시 생성되는 모달창 삭제

---

src/components/step/Step0Component.jsx

- Step0Component에서 초기 렌더링 시 한 번 새로고침하도록 임시로 설정

[#107] 이전 Step에서 Step2Page로 라우팅 시 작은 페이지로 인해 포맷이 맞지 않는 문제

---

src/components/step/Step2Component.jsx
src/components/step/Step2RightSideComponent.jsx

- handleDragEnd 함수에서 지문 그룹 업데이트 시 깊은 복사를 통해 새로운 객체를 생성하도록 수정
- handleDragEnd 함수에서 item의 index를 가져 오는 로직 수정

[#109] feat(step2): Step2에서 Drag & Drop 시 두 번째 지문부터 itemId가 undefined로 나오는 문제 해결

---

src/App.jsx

[#113] 서비스 타이틀을 B셀파로 사용하도록 변경

---

src/components/step/Step0Component.jsx

refactor(step0): 선택한 시험지 편집시 step2로 이동

---

src/components/common/ExamSummaryComponent.jsx
src/components/step/Step2RightSideComponent.jsx

-  Step2RightSideComponent로부터 ExamSummaryComponent 분리

[#116] Step3에서의 재사용을 위해 Step2RightSideComponent의 시험지 요약 부분 컴포넌트 분리

---

src/components/common/ExamSummaryComponent.jsx
src/components/common/QuesionTypeCountComponent.jsx

- ExamSummaryComponent로부터 QuesionTypeCountComponent 분리

[#118] Step3에서의 재사용을 위해 ExamSummaryComponent의 난이도 별 개수 출력 컴포넌트 분리

---

src/components/step/Step0Component.jsx
src/hooks/useCustomMove.jsx

- step0로 절차없이 한 번에 요청시
- main에서 bookId 선택하지 않았기 때문에 main으로 다시 돌려보냄

feat(step0): step0로 바로 요청했을시에 대한 대응 추가

---

src/components/MainComponent.jsx

feat(main): 추가도서 부분 삭제

---

src/components/common/ExamSummaryComponent.jsx
src/components/step/Step2RightSideComponent.jsx

- handleScrollToQuestion 함수 추가

[#116, #117] 누락된 handleScrollToQuestion 함수 추가

---

src/components/common/ExamSummaryComponent.jsx
src/components/step/Step2RightSideComponent.jsx

[#116, #117] 누락된 groupedItems 파라미터 추가

---

src/api/step2Api.js
src/components/common/ExamSummaryComponent.jsx
src/components/step/Step2Component.jsx

- step2Api.js
- ExamSummaryComponent.jsx

[#126] Step0으로부터 받아 온 시험지 정보를 통해 Step2에서 문제 이미지 목록을 불러 오는 기능 추가

---

src/components/step/Step2Component.jsx
src/components/step/Step3Component.jsx
src/slices/examDataSlice.js

- examDataSlice.js
- Step3Component.jsx

[#128] Step2에서 Step3로 전송하는 데이터 목록과 Slice 데이터 목록에 총 문제 수 추가

---

src/components/step/Step2Component.jsx

[#130] Step0으로부터 Step2로 시험지 문제 목록을 받아 오는 경우 재검색 버튼 숨김 처리

---

src/api/step2Api.js
src/components/step/Step2Component.jsx
src/components/step/step1/Step1Component.jsx

Feat/han step1,step2 수정 후 재업로드

Feat/han step1,step2 수정 후 재업로드

---

src/api/step2Api.js
src/components/step/Step2Component.jsx

Step1,2  마지막 수정 후 업로드

---

src/api/step2Api.js

Step2 APi.js 수정 후 업로드

---

src/components/step/Step2Component.jsx
src/components/step/Step2SimilarItemsComponent.jsx

- 검색된 유사 문제가 없을 경우 모달창을 띄우도록 수정

[#141] Step2의 유사 문제를 가져오는 기능에서 검색된 유사 문제가 없을 경우 모달창을 띄우도록 수정

---

src/components/step/Step2Component.jsx
src/components/step/Step2DeletedItemsComponent.jsx
src/components/step/Step2RightSideComponent.jsx
src/components/step/Step2SimilarItemsComponent.jsx

[#145] Step2의 유사 문제와 삭제된 문제를 다시 추가하는 기능 추가

---

package-lock.json
package.json
src/components/user/JoinComponent.jsx
src/join.json
src/util/validator.js

feat(user): validation 기능 추가

---

src/components/user/JoinComponent.jsx

- validation 시 에러 발생했을 때 모달로 알리기 추가

feat(user): validation 시 에러 발생 했을때 모달 추가

---

src/api/step0Api.js

- api 요청 주소 리팩터링
- external 상수로 변경

refactor(step0): api 요청 주소 리팩터링

---

src/hooks/useCustomMove.jsx

- useCustomMove 에 navigate import 추가

fix(hook-move): useCustomMove 임포트 추가

---

src/components/step/step1/DifficultyDisplay.jsx
src/components/step/step1/Step1Component.jsx

Step1 To Step2 체크된 데이터 전달 완료

---

src/api/kakaoApi.js
src/components/common/DrawerComponent.jsx
src/components/common/TextFieldComponent.jsx
src/components/user/JoinComponent.jsx
src/components/user/KakaoLoginComponent.jsx
src/pages/user/KakaoRedirectPage.jsx
src/router/root.jsx
src/slices/loginSlice.jsx

feat(user): 소셜로그인 기능 추가(카카오)

---

src/api/config.js
src/api/step2Api.js
src/assets/css/errorReportModal.css
src/components/common/ErrorReportModalComponent.jsx
src/components/step/Step2Component.jsx
src/components/step/Step2DeletedItemsComponent.jsx
src/components/step/Step2SimilarItemsComponent.jsx

- 오류 신고 버튼 클릭 시 오류 신고 모달 창 띄우기
- 오류 유형, 이미지, 내용 입력
- 신고하기 버튼 클릭 시 서버로 오류 신고 요청 전송
- 오류 신고를 취소하려 할 때 X 버튼을 눌러 취소하기

[#153] Step2의 문제 목록, 유사 문항, 삭제 문항에서의 오류 신고 기능 추가

---

src/components/step/step1/Step1Component.jsx

localhost에서 back단서버로 url변경

---

src/components/step/step1/Step1Component.jsx

feat : Step1 최신화 10.30 21:42

---

src/components/step/step1/Step1Component.jsx

feat : Step1 단원 선택시 출처,평가영역,문제형태 선택되게 수정

feat : Step1 단원 선택시 출처,평가영역,문제형태 선택되게 수정

---

src/components/common/ErrorReportModalComponent.jsx
src/components/step/Step2Component.jsx

[#163] Step2에 Step1에서 넘어 온 데이터 연동

---

src/components/common/ChapterScopeModalComponent.jsx
src/components/step/Step2Component.jsx

- ChapterScopeModalComponent.jsx

[#166] Step2의 출제범위 버튼을 누르면 선택된 단원들의 목록이 표시되는 기능 추가

---

src/components/common/ChapterScopeModalComponent.jsx
src/components/common/ErrorReportModalComponent.jsx

[#168] Step2에서 오류 신고 성공 시 성공 메시지, 중복 신고 시 중복 메시지를 표시하는 기능 추가

---

src/components/common/DrawerComponent.jsx
src/components/step/Step0Component.jsx

- step0
- useLocation 변수로 받는 것으로 수정
- user
- 로그인 버튼 -> 로그인 및 회원가입으로 변경

refactor(step0,user): step0 useLocation 변수로 받음 및 로그인 버튼명 변경

---

src/components/step/step1/DifficultyDisplay.jsx
src/components/step/step1/Step1Component.jsx

Step1 문제 자동 구성 구현

---

src/components/step/step1/Step1Component.jsx

Step1 뒤로가기 임시 수정

---

src/components/step/step1/DifficultyDisplay.jsx
src/components/step/step1/Step1Component.jsx

step1 데이터 로딩 추가 및 문제 수 자동구성 수정

step1 데이터 로딩 추가 및 문제 수 자동구성 수정

---

src/components/step/step1/Step1Component.jsx

Step1 To Step2 API 형식 수정한거 원위치

Step1 To Step2 API 형식 수정한거 원위치

---

src/components/step/Step4PComponentBeta2.jsx

PDF 변수명 수정

---

src/components/step/step1/Step1Component.jsx

Step1 모두 수정

---

src/components/step/step1/Step1Component.jsx

[#183] Step1에서 API 요청 시 questions/external/chapters가 아닌 question-images/external/chapters에 요청을 보내도록 변경

---

src/components/step/step1/Step1Component.jsx

Step1 전체선택 체크시 모두 선택 및 아코디언 펼치기, 해당하는 문제 수만큼 문제 보내기 수정

Step1 전체선택 체크시 모두 선택 및 아코디언 펼치기, 해당하는 문제 수만큼 문제 보내기 수정

---

src/api/step2Api.js
src/components/step/Step2Component.jsx

[#187] Step2에서 재검색 시 난이도 별 개수가 조정된 서버 엔드포인트로 요청하도록 변경

---

src/components/step/step1/Step1Component.jsx

[#189] Step1에서 Step2로 전송되는 데이터에 minorClassification 추가

---

src/components/step/Step2Component.jsx
src/components/step/step1/Step1Component.jsx

[#191] Step1에서 Step2로 전송되는 counts 데이터에 최상과 최하 난이도 정보 추가

---

src/components/step/step1/DifficultyDisplay.jsx
src/components/step/step1/Step1Component.jsx

Step1 마지막 수정

---

src/components/step/step1/Step1Component.jsx

Step1 문제수 변경시 난이도별 문제수 수정

---

src/components/step/step1/Step1Component.jsx

Step1 문제수 변경시 난이도별 문제수 최종 수정

---

src/components/step/Step2Component.jsx

[#197] Step2의 URL로 직접 접근 시 접근 불가 모달창을 활성화하고 메인 페이지로 이동시키는 기능 추가

---

src/components/step/Step2Component.jsx

[#199] 유사 문제나 삭제 문항을 선택했을 때도 비정상적인 접근 모달이 활성화되는 문제 해결

---

src/components/common/ExamSummaryComponent.jsx
src/components/step/Step2Component.jsx

[#204] Step2에서 드래그 앤 드롭으로 문항 순서를 변경하거나 문항 삭제 시 정렬 상태가 사용자 정렬로 변경되는 기능 추가

---

src/components/step/Step2Component.jsx

- useRef를 통해 리렌더링 여부에 관계없이 step1Data를 갱신하지 않도록 변경

[#206] Step2에서 유사 문제 또는 삭제 문항 탭으로 넘어갈 때 itemsRequestForm이 초기화되는 문제 해결

---

src/components/common/DrawerComponent.jsx

[#210] 메인 페이지에 EX셀파 링크 추가

---

src/components/step/Step2Component.jsx

- minorClassification 값의 존재 유무 판단을 null이 아닌 배열의 length로 하도록 변경

[#212] Step0에서 Step2로 넘어갈 때도 재검색 버튼이 활성화되는 문제 해결

---

src/components/step/Step4ComponentBeta2.jsx
src/pages/step/Step4PageBeta.jsx

- Step4ComponentBeta2 renaming
- handlePrint() 수정

PDF print 수정

---

package-lock.json
package.json
src/components/common/DrawerComponent.jsx
src/main.jsx

fix(user): 로그인 및 회원가입 기능 분리

---

src/components/common/DrawerComponent.jsx

[#224] 메인 페이지의 EX셀파 링크 URL 변경

---

src/components/common/AccordionComponent.jsx
src/components/common/TableComponent.jsx
src/components/step/Step0Component.jsx

fix(step0): url로 접속하면 선택했던 bookId가 없어서 main으로 돌려보내도록 수정

---

src/components/step/Step4Component.jsx

PDF 컴포넌트 수정

---

src/components/step/step1/Step1Component.jsx

Step1 to Step  변수 수정

---

src/api/step0Api.js
src/util/jwtUtil.jsx

fix(jwt): jwt유틸 작동할 수 있도록 수정

---

src/components/step/step1/DifficultyDisplay.jsx
src/components/step/step1/Step1Component.jsx

Step1 톱니바귀 수정시 자동 구성 전 검증

---

src/components/step/step1/Step1Component.jsx

Step1 1380 에러 수정

---

src/components/step/step1/Step1Component.jsx

11.04 Step1 최종본

---

src/components/common/DrawerComponent.jsx
src/components/user/JoinComponent.jsx
src/router/root.jsx

feat(user): 회원가입시 선택지 추가

---

src/components/user/JoinComponent.jsx

- 회원가입시 class 파라미터명 변경
- class -> clazz

refactor(user): 회원가입시 class 파라미터명 변경

---

public/googledff038da5859f610.html

[#242] 구글 서치에 도메인 등록

---

src/components/step/step1/Step1Component.jsx

Step1 jwtAxios로 변경

---

src/api/step2Api.js

Step2api jwtAxios로 변경

---

src/components/step/step1/Step1Component.jsx

Step1 자동 구성 및 문제충분시 모달창 수정

---

src/components/step/step1/DifficultyDisplay.jsx
src/components/step/step1/Step1Component.jsx

Step1 난이도 구성 에러 모두 해결

---

src/components/step/step1/DifficultyDisplay.jsx

Step1 난이도 별 문제수 자동 비율 할당 최종본

---

src/components/step/step1/DifficultyDisplay.jsx

11.05 19:45 Step1 난이도 별 문제수 자동 비율 할당 최종본

11.05 19:45 Step1 난이도 별 문제수 자동 비율 할당 최종본

---

src/components/common/CardComponent.jsx

[#254] 비로그인 시 시험지 만들기 기능을 사용할 수 없도록 변경

---

src/components/step/Step2Component.jsx

[#261] Step1으로 이동하는 데이터에 bookId 포함

---

src/components/step/Step3Component.jsx

[#263] Step2에서 Step1으로 이동하는 데이터 수정

---

src/components/step/Step2Component.jsx

[#267] Step2에서 재검색 시 유사 문제와 삭제 문항 목록을 삭제하도록 변경

---

src/components/step/Step2Component.jsx

[#269] Step2에서 지문의 문제가 한 개일 때 지문 상단의 문제 번호를 단축해서 표시하도록 변경

---

src/components/step/Step2Component.jsx

[#271] Step2의 좌우 크기를 컴포넌트 크기에 맞도록 조정

---

src/components/common/DrawerComponent.jsx
src/components/step/step1/DifficultyDisplay.jsx
src/components/step/step1/Step1Component.jsx

Step1 화면 배율 수정

---

src/components/step/Step2Component.jsx

[#274] Step2 컴포넌트의 크기 조정

---

src/components/step/Step2Component.jsx

[#281] Step2 컴포넌트의 비율 수정에 zoom을 적용하지 않도록 변경

---

src/components/step/Step2Component.jsx

[#281] Step2 컴포넌트의 비율 변경

---

src/api/step4Api.js
src/components/step/Step4Component.jsx

- 비동기 데이터 받는 로딩 이슈
- 비동기 함수 호출 오류

PDF 실제 데이터 받아오는 시행착오 중

---

src/components/step/Step4Component.jsx

PDF Step4 컴포넌트 수정

---

src/components/MainComponent.jsx
src/components/step/Step0Component.jsx

Step0 내 시험지 목록 가져온후 뿌려주는거 까지 확인함

Step0 내 시험지 목록 가져온후 뿌려주는거 까지 확인함

---

src/components/common/ExamSummaryComponent.jsx
src/components/step/Step2Component.jsx
src/util/CommonResource.jsx

- 수직 정렬 방식을 start에서 center로 변경

[#289] 문제지 요약 클릭, 유사 문제 추가, 삭제 문항 추가 시 스크롤되면서 화면도 이동하는 문제 해결

---

src/api/step4Api.js
src/components/step/Step4Component.jsx

PDF 컴포넌트 기능 구현 완성

---

src/api/step4Api.js
src/components/common/ExamCardComponent.jsx

- ExamCardComponent에 Step4Component 이전

PDF 컴포넌트 붙이기

---

src/components/common/ExamCardComponent.jsx
src/components/step/Step4Component.jsx

- ExamCardComponent 하위로 Step4Component 이전
- examId만 제대로 받아주면 됨

PDF 컴포넌트 분리

---

src/components/common/MainSelectComponent.jsx

메인 페이지 미 로그인시 시험지보관함 클릭하면 모달창 팝업 띄우기 추가

메인 페이지 미 로그인시 시험지보관함 클릭하면 모달창 팝업 띄우기 추가

---

src/api/step4Api.js
src/components/common/ExamCardComponent.jsx
src/components/step/Step4Component.jsx

- API 주소 OK
- 페이지 로드할 때 모든 데이터 다 가져오는 방식 의문

PDF 실제 데이터 받아 출력까지 완료

---

src/api/step4Api.js
src/components/common/ExamCardComponent.jsx

- 데이터 과부화 검토
- 한 페이지 넘는 지문 PDF 처리 곤란
- 반 페이지씩 출력 가능한지 검토

PDF 버튼그룹으로 일시적 변경

---

src/components/common/ExamCardComponent.jsx
src/components/common/ExamStorageComponent.jsx

시험지 보관함 해당 과목에대한 데이터 조회와 해당하는 과목에 대한 교과서 이미지 추가

시험지 보관함 해당 과목에대한 데이터 조회와 해당하는 과목에 대한 교과서 이미지 추가

---

src/components/MainComponent.jsx

리스트 3개씩 출력

---

src/components/common/ExamCardComponent.jsx
src/components/step/Step4ComponentAll.jsx
src/components/step/Step4ComponentAnswer.jsx
src/components/step/Step4ComponentQuestion.jsx
src/pages/step/Step4Page.jsx

PDF 문서 구조 수정

---

src/components/step/Step4ComponentAll.jsx
src/components/step/Step4ComponentAnswer.jsx
src/components/step/Step4ComponentQuestion.jsx

PDF 유형별 컴포넌트 구조 변경

---

src/components/step/step1/Step1Component.jsx

Step1 아코디언 라인 맞춤

---

src/components/common/DrawerComponent.jsx

메인페이지 사이드바 컴포넌트 정렬

---

src/components/common/DrawerComponent.jsx

메인페이지 사이드바(유저 정보)

---

src/components/common/DrawerComponent.jsx

- 새로고침 -> 유저명 저장 안되는 이슈
- 로그인시 localStorage에 유저명 저장
- 로그아웃시 제거

메인페이지 사이드바(유저명) 저장

---

package-lock.json
package.json
src/components/step/Step4ComponentAnswer.jsx
src/components/step/Step4ComponentQuestion.jsx

PDF 수식 처리 이슈

---

src/components/common/ErrorReportModalComponent.jsx

- 모달 상태 관리를 위한 useEffect 훅 추가
- handleClose 함수의 useState 훅 호출 추가

[#315] Step2에서 오류 신고 후 오류 신고 모달이 초기화되지 않는 문제 해결

---

src/components/common/ExamSummaryComponent.jsx

[#318] Step2의 우측 파트 문제지 요약 부분 크기 조정

---

src/components/common/ExamSummaryComponent.jsx

[#318] Step2의 우측 파트 문제지 요약 부분 크기 조

---

src/components/common/ExamSummaryComponent.jsx

feat(step2): Step2의 우측 파트 문제지 요약 부분 크기 조정 (#318)

---

src/components/step/step1/Step1Component.jsx

Step1 CSS 새로 적용

---

src/components/common/ExamSummaryComponent.jsx

[#332] Step2의 우측 파트 문제지 요약 부분 헤더 위치 조정

---

src/components/common/DrawerComponent.jsx

메인페이지 css 한글 깨짐 해결

---

src/components/step/step1/Step1Component.jsx

Step1 최종 수정

---

src/components/common/DrawerComponent.jsx

MainPage 로그인 슬라이드 한글깨짐 및 새로고침없이 바로 유저네임 출력 수정

MainPage 로그인 슬라이드 한글깨짐 및 새로고침없이 바로 유저네임 출력 수정

---

src/components/common/DrawerComponent.jsx

시험지 보관함 유저네임 겹치는 부분 해결

---

src/components/step/Step4ComponentAll.jsx

PDF ALL 수식 렌더링

---

src/components/common/ExamSummaryComponent.jsx

[#345] Step2 드래그 앤 드롭의 움직이는 바 위치 조정

---

src/components/step/Step3SuccessComponent.jsx

bookId 관련 문제 수정
배포용 이미지 경로 임시 삭제

fix: Step3SuccessComponent

---

src/components/step/step1/DifficultyDisplay.jsx

Step1 난이도 설정 에서 초기화 버튼 클릭시 10,10,10 으로 초기화

Step1 난이도 설정 에서 초기화 버튼 클릭시 10,10,10 으로 초기화

---

src/components/common/TableComponent.jsx

fix: TableComponent

---

src/components/common/ExamCardComponent.jsx

fix: ExamCardComponent

---

src/components/common/ExamStorageComponent.jsx

fix: ExamStorageComponent

---

README.md

- 프로젝트 설명
- 프로젝트 기간
- 구성원
- 관련 URL
- B셀파 서비스
- B셀파 CI/CD 파이프라인
- 발표 자료
- 시연 영상
- B개발자팀 노션
- 아키텍처
- ERD
- 사용 기술

[#361] README.md 추가

---

src/components/step/Step2RightSideComponent.tsx
src/components/step/Step2SimilarItemsComponent.tsx

- Step2SimilarItemsComponent.tsx

[#365] Step2SimilarItemsComponent를 타입스크립트로 리팩터링

---

src/components/common/ChapterScopeModalComponent.tsx
src/components/step/Step2Component.tsx

- ChapterScopeModalComponent.tsx

[#365] ChapterScopeModalComponent를 타입스크립트로 리팩터링

---

src/components/common/ExamSummaryComponent.tsx
src/components/step/Step2Component.tsx

[#365] ExamSummaryComponent를 타입스크립트로 리팩터링

---

src/components/common/ConfirmationModal.tsx
src/components/step/Step2Component.tsx

[#365] ConfirmationModal를 타입스크립트로 리팩터링

---

src/components/common/DifficultyCountComponent.tsx
src/components/step/Step2Component.tsx
src/util/difficultyColorProvider.ts

[#365] difficultyColorProvider를 타입스크립트로 리팩터링
